export const temporaryDefaultValues = {
  type: "Temp",
  vehicleDetails: {
    registrationNumber: "",
    type: "",
    make: "",
    model: "",
    year: "",
    fuel: "",
    transmission: "",
    doors: "",
    colour: "",
    worth: "",
    trackingDevice: "No",
    alarmImmobiliser: "No",
    importedVehicle: "No",
    vehicleModified: "No",
    vehicleModifications: [],
    purchaseDate: "",
    legalOwner: "",
    owner: "Policyholder",
    ownerOther: "",
    registeredKeeper: "Policyholder",
    registeredKeeperOther: "",
    apiData: null,
  },
  coverDetails: {
    type: "",
    period: "",
    startDate: "",
    startTime: "",
  },
  userDetails: {
    firstName: "",
    surname: "",
    email: "",
    phone: "",
    dateOfBirth: "",
    postCode: "",
    address: "",
    employmentStatus: "",
    occupation: "",
    industry: "",
  },
  carUsage: {
    industry: "",
    keepingCarDuringDay: "",
    keepingCarDuringNight: "",
    usageType: "",
    licenseType: "",
    licenseHeld: "",
    licenseNumber: "",
    NCB: "",
    voluntaryExcess: "",
    criminalConvictions: null,
    medicalConditions: null,
    insuranceCancelledOrClaimRefusedOrPolicyVoided: null,
  },
  terms: {
    acceptTerms: false,
    acceptMarketing: false,
  },
};

export const impoundDefaultValues = {
  type: "Impound",
  vehicleDetails: {
    registrationNumber: "",
    type: "",
    make: "",
    model: "",
    year: "",
    fuel: "",
    transmission: "",
    doors: "",
    colour: "",
    worth: "",
    trackingDevice: "No",
    alarmImmobiliser: "No",
    importedVehicle: "No",
    vehicleModified: "No",
    vehicleModifications: [],
    purchaseDate: "",
    legalOwner: "",
    owner: "Policyholder",
    ownerOther: "",
    registeredKeeper: "Policyholder",
    registeredKeeperOther: "",
    apiData: null,
  },
  coverDetails: {
    impoundType: "",
    startDate: "",
    startTime: "10:00",
  },
  userDetails: {
    firstName: "",
    surname: "",
    email: "",
    phone: "",
    dateOfBirth: "",
    postCode: "",
    address: "",
    employmentStatus: "",
    occupation: "",
    industry: "",
  },
  carUsage: {
    industry: "",
    keepingCarDuringDay: "",
    keepingCarDuringNight: "",
    usageType: "",
    licenseType: "",
    licenseHeld: "",
    licenseNumber: "",
    NCB: "",
    voluntaryExcess: "",
    criminalConvictions: false,
    medicalConditions: false,
    insuranceCancelledOrClaimRefusedOrPolicyVoided: false,
  },
  terms: {
    acceptTerms: false,
    acceptMarketing: false,
  },
};

export const annualDefaultValues = {
  type: "Annual",
  vehicleDetails: {
    registrationNumber: "",
    type: "",
    make: "",
    model: "",
    year: "",
    fuel: "",
    transmission: "",
    doors: "",
    colour: "",
    worth: "",
    trackingDevice: "No",
    alarmImmobiliser: "No",
    importedVehicle: "No",
    vehicleModified: "No",
    vehicleModifications: [],
    purchaseDate: "",
    legalOwner: "",
    owner: "Policyholder",
    ownerOther: "",
    registeredKeeper: "Policyholder",
    registeredKeeperOther: "",
    apiData: null,
  },
  coverDetails: {
    level: "",
    startDate: "",
  },
  optionalExtras: {
    courtesyCar: null,
    breakdownCover: null,
    foreignUseCover: null,
  },
  userDetails: {
    firstName: "",
    surname: "",
    email: "",
    phone: "",
    dateOfBirth: "",
    postCode: "",
    address: "",
    employmentStatus: "",
    occupation: "",
    industry: "",
  },
  carUsage: {
    industry: "",
    keepingCarDuringDay: "",
    keepingCarDuringNight: "",
    usageType: "",
    otherVehicles: null,
    otherVehiclesType: "",
    hasAdditionalQualifications: null,
    additionalQualificationType: "",
    qualificationMonth: "",
    qualificationYear: "",
    licenseType: "",
    licenseHeld: "",
    licenseNumber: "",
    NCB: "",
    voluntaryExcess: "",
    ownsHome: null,
    childrenUnder16: null,
    livedInUKSinceBirth: null,
    hasAdditionalDrivers: null,
    additionalDrivers: [],
    criminalConvictions: null,
    medicalConditions: null,
    insuranceCancelledOrClaimRefusedOrPolicyVoided: null,
  },
  terms: {
    acceptTerms: false,
    acceptMarketing: false,
  },
};

export const STEPS = {
  VEHICLE: 1,
  COVER: 2,
  PERSONAL: 3,
  REVIEW: 4,
};
